app.services.greeting.message: Hello World!!!

spring:
  datasource:
    username: root
    password: Bie1018751Bie
    url: jdbc:mysql://localhost:3306/company
    driver-class-name: com.mysql.jdbc.Driver